# Generated by Django 4.2.4 on 2023-09-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Moscow, Pizzeria Pizza-Casa', max_length=40),
        ),
    ]
