# Generated by Django 4.2.4 on 2023-08-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_alter_product_avatar_alter_product_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cover',
        ),
    ]
